[package]
name = "markup_fmt"
version = "0.0.0"
edition = "2021"
authors = ["Pig Fang <g-plane@hotmail.com>"]
description = "Configurable HTML/Vue/Svelte formatter."
repository = "https://github.com/g-plane/markup_fmt"
license = "MIT"
exclude = ["/tests"]

[dependencies]
itertools = "0.11"
serde = { version = "1.0", optional = true }
tiny_pretty = "0.1"

[dev-dependencies]
insta = { version = "1.31", features = ["glob"] }
toml = "0.7"

[features]
config_serde = ["serde"]
