[package]
name = "markup_fmt"
version = "0.3.2"
edition = "2021"
authors = ["Pig Fang <g-plane@hotmail.com>"]
description = "Configurable HTML/Vue/Svelte/Jinja/Twig formatter."
repository = "https://github.com/g-plane/markup_fmt"
license = "MIT"
exclude = ["/tests"]

[dependencies]
css_dataset = "0.3"
itertools = "0.11"
serde = { version = "1.0", optional = true }
tiny_pretty = { version = "0.1", features = ["unicode-width"] }

[dev-dependencies]
insta = { version = "1.34", features = ["glob"] }
toml = "0.8"

[features]
config_serde = ["serde"]
