name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - run: |
          cargo build --release -p dprint_plugin_markup --target wasm32-unknown-unknown
          cp target/wasm32-unknown-unknown/release/dprint_plugin_markup.wasm dprint_plugin/deployment/plugin.wasm
      - name: Publish dprint plugin
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dprint_plugin/deployment/plugin.wasm
            dprint_plugin/deployment/schema.json
      - name: Publish crates
        run: cargo publish -p markup_fmt
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
          run_install: true
      - name: Publish npm package
        run: |
          cp target/wasm32-unknown-unknown/release/dprint_plugin_markup.wasm dprint_plugin/deployment/npm/plugin.wasm
          pnpm -F dprint-plugin-markup publish --no-git-checks --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
